### PR TITLE
Update MinionBase.php

### PR DESCRIPTION
**Pull request by Mcbeany**
my mistake

### CODE REVIEW

**Comment by AIPTU** [comment]
Well you should make changes to one commit directly rather than one by one

**Comment by Mcbeany** [comment]
> Well you should make changes to one commit directly rather than one by one

my bad xd

**Comment by AIPTU** [comment]
Can you recommit #2 #3 #4 #5  with one commit to make it easier ?

**Comment by Mcbeany** [comment]
ok

**Pull request closed without merging**
